#:schema node_modules/wrangler/config-schema.json
name = "remodeling-tracker"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static" 

[[d1_databases]]
binding = "DB"
database_name = "remodeling-tracker-db"
database_id = "06fc653a-168e-47e4-885d-edfb0591b9ae" 

[[r2_buckets]]
bucket_name = "expenses-db"
binding = "IMAGES"